package com.grahamedgecombe.advent2025

import com.grahamedgecombe.advent2025.day7.Day7
import kotlin.test.Test
import kotlin.test.assertEquals

class Day7Test {
    @Test
    fun testPart1() {
        assertEquals(21, Day7.solvePart1(TEST_INPUT))
        assertEquals(1711, Day7.solvePart1(PROD_INPUT))
    }

    private companion object {
        private val TEST_INPUT = Day7.parse("""
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent())
        private val PROD_INPUT = Day7.parse()
    }
}
